env:
  global:
    - secure: KbXw73rCC0fN4invitqpDHyKl8jY4ZBgwsf2p/Rp/EuMH0ViLB2ZBQoY3hbo+nTaTdIh+GaDnskp8ajjd0i5VjmCva5iHQXLild/tyJ692hMp21n2kx6uj8nFznrZc9PoeYsln9Y/3Hd1XEt46JHvm9bOoNFoq5XO+oNYIFlqbo=
language: rust

script:
  - rustc --version
  - cargo --version
  - cargo build --verbose && cargo test --verbose
  - cargo doc --verbose && mv target/doc doc

after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh


notifications:
  email:
    recipients:
        - shailesh@indigits.com
        - shaileshk@gmail.com

# whitelist of branches
branches:
  only:
    - master
    #- stable
